[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python crear_categorias.py && python init_db.py && gunicorn app:app --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE" 